### PR TITLE
Converted some sub components in Access folder to use hooks

### PR DESCRIPTION
**Pull request by wongband**
Converted the following components:
- AccessList
- AccessListItem
- AccessTable
- AssignAccess
- RevokeAccess

### CODE REVIEW

**Review by sprucely — COMMENTED** [review]
I only glanced at the code, but ran it locally and everything seems to work for me.

**Review by jSylvestre — CHANGES_REQUESTED** [review]
When I create a new access, the list isn't updated unless I refresh the page.

**Comment by wongband** [comment]
@jSylvestre Should be fixed in this push ^^^

**Review by jSylvestre — CHANGES_REQUESTED** [review]
@wongband The list update appear to be fixed.
But.... When creating an access, the add tags (click on tags, then click on the tag) is mostly not working.

image

**Review by jSylvestre — APPROVED** [review]
@wongband Looks good to me, but wait for @srkirkland to take a look at the code.

**Review by srkirkland — APPROVED** [review]

**Pull request merged**
