### PR TITLE
Converted some sub components in the Equipment folder to use hooks

### PR DESCRIPTION
**Pull request by wongband**
Converted the following components:
- AssignEquipment
- RevokeEquipment
- EquipmentAssignmentValues
- EquipmentList
- EquipmentListItem
- EquipmentTableContainer

### CODE REVIEW

**Review by srkirkland — APPROVED** [review]

**Review by jSylvestre — CHANGES_REQUESTED** [review]
Search for tags breaks:
image

image

**Comment by wongband** [comment]
@jSylvestre what other tags do we have besides Student? I can only see Student as an option

**Comment by jSylvestre** [comment]
> @jSylvestre what other tags do we have besides Student? I can only see Student as an option

@wongband Tags are dynamic. They are added by a departmental admin to the team.

**Comment by wongband** [comment]
Ahh I see I was just curious

**Review by jSylvestre — APPROVED** [review]

**Pull request merged**
