### PR TITLE
create auto labeler action

### PR DESCRIPTION
**Pull request by srkirkland**

### CODE REVIEW

**Comment by jSylvestre** [comment]
Bad github bot

**Comment by srkirkland** [comment]
You mean great bot!

**Comment by jSylvestre** [comment]
> You mean great bot!

It added a DB change label to a PR with no DB change?

**Comment by srkirkland** [comment]
> > You mean great bot!
> 
> It added a DB change label to a PR with no DB change?

I adds a DB change label any time a file in the `Keas.Core/Domain` folder is changed.  It doesn't always mean DB change but just warns you that domain files were changed.  Really this is just to test/play with GitHub actions, but I also thought it was a cool idea.

**Pull request merged**
