### PR TITLE
Got rid of loosing filtering for equipment table

### LINKED ISSUE #962: Loosing filtering
Steven Barkey 7:52 AM

After filtering equipment by last name, clicking on the details button for a piece of equipment clears the filtering.  (likely happens with all column filters).

### PR DESCRIPTION
**Pull request by wongband**
closes #962 

I removed the `fetchDetails` function since the selected equipment passed in the component is the exact same as the equipment returned from `fetchDetails`. I think that this is not necessary and it does not remove the filter as well.

### CODE REVIEW

**Comment by sprucely** [comment]
> 
> 
> You have removed the error checking.
> I don't really like that. But I'll let Scott decide.

@jSylvestre Some of the error checking in that removed method can be found at https://github.com/ucdavis/Peaks/blob/79c6869edaca67a7c307830f54116248465919aa/Keas.Mvc/ClientApp/components/Equipment/EquipmentContainer.tsx#L79-L87

But, yeah, it probably would be good to add in the toast with the "Not found" message.

**Comment by jSylvestre** [comment]
> @jSylvestre Some of the error checking in that removed method can be found at

@sprucely That is getting the list of equipment. Not the individual equipment I believe. Two different actions.

**Comment by wongband** [comment]
Should we do error checking if the `selectedEquipment` is null? From the original code it always fetches for the equipment regardless if the `selectedEquipment` is not null.

**Comment by sprucely** [comment]
> 
> 
> > @jSylvestre Some of the error checking in that removed method can be found at
> 
> @sprucely That is getting the list of equipment. Not the individual equipment I believe. Two different actions.

Yes, it's getting the list of equipment, but it's an element of that list which is being passed to EquipmentDetails.

**Pull request merged**
